name: Run all tests

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  test:
    name: SonarQube
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull Kafka Docker Image
        run: docker pull apache/kafka:4.1.0

      - name: Start Kafka
        run: |
          docker run -d --name kafka \
            -p 9092:9092 \
            -e KAFKA_NODE_ID=1 \
            -e KAFKA_PROCESS_ROLES=broker,controller \
            -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT \
            -e KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 \
            -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 \
            -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
            -e KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
            -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
            -e KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0 \
            apache/kafka:4.1.0

      - name: Wait for Kafka to start
        run: |
          echo "Waiting for Kafka to start..."
          sleep 20

      - name: Build Docker Image
        run: docker build -t upload-service .

      - name: Run Jest Tests inside Docker
        env:
          PORT: ${{ secrets.PORT }}
          APP_EMAIL: ${{ secrets.APP_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
        run: |
          docker run --rm \
            -e PORT \
            -e APP_EMAIL \
            -e APP_PASSWORD \
            -e CLOUDINARY_API_KEY \
            -e CLOUDINARY_API_SECRET \
            -e CLOUDINARY_CLOUD_NAME \
            -e KAFKA_BROKER \
            -v $PWD/coverage:/app/coverage \
            upload-service npm run coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Stop Kafka
        if: always()
        run: |
          docker stop kafka || true
          docker rm kafka || true